# Generated by Django 3.2.4 on 2021-07-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.breed_n')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.customer_n')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.employee_n')),
            ],
        ),
        migrations.CreateModel(
            name='Petstore_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.location_n')),
            ],
        ),
        migrations.AddField(
            model_name='employee_n',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.location_n'),
        ),
        migrations.AddField(
            model_name='employee_n',
            name='petstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.petstore_n'),
        ),
        migrations.AddField(
            model_name='customer_n',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.location_n'),
        ),
        migrations.CreateModel(
            name='Category_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('petstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.petstore_n')),
            ],
        ),
        migrations.AddField(
            model_name='breed_n',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category_n'),
        ),
    ]
