# Generated by Django 3.2.4 on 2021-07-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breed_n',
            new_name='Breed',
        ),
        migrations.RenameModel(
            old_name='Category_n',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Customer_n',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Employee_n',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Location_n',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Petstore_n',
            new_name='Petstore',
        ),
        migrations.RenameModel(
            old_name='Sale_n',
            new_name='Sale',
        ),
    ]
