# Generated by Django 3.2.4 on 2021-06-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.breed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Petstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postgresql.location')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postgresql.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='petstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.petstore'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postgresql.location'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('petstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.petstore')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.category'),
        ),
    ]
